window.IDEAL_BUILD='20260718-rotacao-final';
const STORE={groups:'ideal_groups_v5',regions:'ideal_regions_v5',models:'ideal_models_v5',activity:'ideal_activity_v5',messageIndex:'ideal_message_index_v1'};
const DAY=86400000;
const $=id=>document.getElementById(id);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const clean=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const normUrl=url=>{url=String(url||'').trim();if(!url)return'';if(!/^https?:\/\//i.test(url))url='https://'+url;try{const u=new URL(url);const m=u.pathname.match(/\/groups\/([^/?#]+)/i);return m?'https://www.facebook.com/groups/'+m[1]:''}catch{return''}};
const DEFAULT_REGIONS=['Campo Grande','Cosmos','Paciência','Santa Cruz','Méier','Bangu','Realengo','Senador Camará','Santíssimo','Inhoaíba','Guaratiba','Sepetiba','Barra da Tijuca','Recreio dos Bandeirantes','Jacarepaguá','Taquara','Freguesia','Pechincha','Curicica','Praça Seca','Madureira','Irajá','Tijuca','Vila Isabel','Penha','Pavuna','Copacabana','Ipanema','Leblon','Botafogo','Flamengo','Centro','Lapa','Nova Iguaçu','Duque de Caxias','Belford Roxo','São João de Meriti','Nilópolis'];
const DEFAULT_MODELS=[`🏠 Proteja e valorize seu imóvel com quem entende do assunto!\n\n✅ Toldos retráteis e fixos\n✅ Coberturas em policarbonato\n✅ Fachadas em ACM\n✅ Instalação profissional\n\n📲 Solicite seu orçamento: {LINK}`,`☀️ Sol forte ou chuva? Temos a solução sob medida para sua casa ou comércio.\n\n✅ Toldos e coberturas\n✅ Fabricação própria\n✅ Atendimento no Rio de Janeiro\n\n👉 Peça seu orçamento: {LINK}`,`🚨 ORÇAMENTO SEM COMPROMISSO\n\nQualidade, proteção e acabamento profissional para seu imóvel.\n\n📲 Fale com a Ideal Toldos: {LINK}`,`🏡 Deixe seu imóvel mais bonito, protegido e valorizado.\n\n✔ Toldos\n✔ Policarbonato\n✔ ACM e letreiros\n\n💬 Solicite seu orçamento: {LINK}`];
let state={groups:[],regions:[],models:[],activity:[],clicks:[],cycle:[],currentIndex:-1,current:null,messageIndex:0,extracted:[],searches:[]};
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}}
function mergeGroups(...lists){const map=new Map();lists.flat().forEach(g=>{if(!g)return;const url=normUrl(g.url||g.link);if(!url)return;const region=String(g.region||g.bairro||g.regiao||'').trim();map.set(url,{...g,id:g.id||('g_'+Math.random().toString(36).slice(2)),name:g.name||g.nome||'Grupo Facebook',url,link:url,region,bairro:region,status:g.status||'pendente',postedAt:g.postedAt||g.lastPostedAt||null})});return[...map.values()]}
function loadLocal(){const legacyMaster=readJSON('ideal_admin_master_v1',{}),legacyFix=readJSON('ideal_admin_fix_v1',{});state.groups=mergeGroups(readJSON(STORE.groups,[]),readJSON('ideal_groups_v4',[]),legacyMaster.groups||[],legacyFix.groups||[]);state.regions=readJSON(STORE.regions,readJSON('ideal_regions_v4',[]));if(!state.regions.length)state.regions=DEFAULT_REGIONS.map(name=>({name,zone:'Rio de Janeiro',goal:50}));state.models=readJSON(STORE.models,readJSON('ideal_models_v4',DEFAULT_MODELS));if(!Array.isArray(state.models)||!state.models.some(x=>String(x||'').trim()))state.models=[...DEFAULT_MODELS];state.activity=readJSON(STORE.activity,[]);state.messageIndex=Math.max(0,Number(readJSON(STORE.messageIndex,0))||0)%4}
function saveLocal(){localStorage.setItem(STORE.groups,JSON.stringify(state.groups));localStorage.setItem(STORE.regions,JSON.stringify(state.regions));localStorage.setItem(STORE.models,JSON.stringify(state.models));localStorage.setItem(STORE.activity,JSON.stringify(state.activity.slice(0,100)));localStorage.setItem(STORE.messageIndex,JSON.stringify(state.messageIndex));const master=readJSON('ideal_admin_master_v1',{});master.groups=state.groups;master.models=state.models;localStorage.setItem('ideal_admin_master_v1',JSON.stringify(master));const fix=readJSON('ideal_admin_fix_v1',{});fix.groups=state.groups;fix.models=state.models;localStorage.setItem('ideal_admin_fix_v1',JSON.stringify(fix))}
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Erro no servidor');return d}
async function sync(){try{const d=await api('/api/groups');state.groups=mergeGroups(state.groups,d.groups||[]);await api('/api/groups/backup',{method:'POST',body:JSON.stringify({groups:state.groups})});saveLocal()}catch(e){console.warn(e.message)}try{const d=await api('/api/clicks');state.clicks=Array.isArray(d.clicks)?d.clicks:[]}catch{state.clicks=[]}}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const titles={dashboard:['Dashboard','Resumo da ferramenta de divulgação'],grupos:['Banco de Grupos','Cadastro, busca e organização dos grupos'],regioes:['Controle de Região','Quantidade de grupos por bairro'],modelos:['Modelos de Postagem','Mensagens com link rastreável'],ciclo:['Ciclo de Divulgação','Postagem por bairro com bloqueio de 24 horas'],relatorios:['Relatórios','Origem dos cliques rastreáveis'],galeria:['Galeria','Fotos por categoria'],clientes:['Clientes','Cadastros recebidos'], 'como-usar':['Como Usar','Passo a passo da ferramenta'],config:['Configurações','Backup e controle de cliques']};$('pageTitle').textContent=titles[page]?.[0]||'Painel';$('pageSubtitle').textContent=titles[page]?.[1]||'';if(page==='relatorios')loadClicks().then(renderReports)}
function countByRegion(name){return state.groups.filter(g=>clean(g.region)===clean(name)).length}
function ensureRegions(){const names=new Set(state.regions.map(r=>clean(r.name)));state.groups.forEach(g=>{if(g.region&&!names.has(clean(g.region))){state.regions.push({name:g.region,zone:'Rio de Janeiro',goal:50});names.add(clean(g.region))}})}
function renderStats(){ensureRegions();$('statGroups').textContent=state.groups.length;$('statRegions').textContent=new Set(state.groups.map(g=>clean(g.region)).filter(Boolean)).size;const today=new Date().toISOString().slice(0,10);$('statPosted').textContent=state.groups.filter(g=>String(g.postedAt||'').slice(0,10)===today).length;$('statGoal').textContent=`${state.groups.length} / ${state.regions.reduce((s,r)=>s+Number(r.goal||50),0)}`;$('groupCountBadge').textContent=`${state.groups.length} grupos`}
function renderRegions(){const html=state.regions.map(r=>{const count=countByRegion(r.name),goal=Number(r.goal||50),pct=Math.min(100,Math.round(count/goal*100));return`<div class="region-item"><header><strong>${esc(r.name)}</strong><span>${count}/${goal}</span></header><small>${esc(r.zone||'')}</small><div class="bar"><span style="width:${pct}%"></span></div></div>`}).join('');$('dashRegions').innerHTML=html;$('regionsGrid').innerHTML=state.regions.map(r=>`<div class="panel"><h3>${esc(r.name)}</h3><p>${countByRegion(r.name)}/${Number(r.goal||50)} grupos</p></div>`).join('')}
function fillRegions(){const opts='<option value="">Selecionar bairro</option>'+state.regions.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join('');['groupRegionSelect','dashRegionSelect','cycleRegionSelect'].forEach(id=>{const el=$(id);if(!el)return;const v=el.value;el.innerHTML=opts;el.value=v});updateSelectedRegion()}
function selectedRegion(){return $('groupRegionSelect')?.value||''}
function updateSelectedRegion(){const r=selectedRegion();$('selectedRegionLabel')&&($('selectedRegionLabel').textContent=r?`Bairro: ${r}`:'Bairro não selecionado');buildSearches()}
function renderGroups(){const q=clean($('filterGroups')?.value||'');const list=state.groups.filter(g=>clean(`${g.name} ${g.region} ${g.url}`).includes(q));$('groupsTable').innerHTML=list.map(g=>{const link=trackingLink(g);return`<div class="data-row"><header><strong>${esc(g.name)}</strong><span>${esc(g.region||'Sem bairro')}</span></header><small>${esc(g.url)}</small><small class="track-link">Link rastreável: ${esc(link)}</small><div class="actions"><a class="btn blue" href="${esc(g.url)}" target="_blank">Abrir grupo</a><button class="btn blue" data-copy-link="${esc(link)}">Copiar link</button><button class="btn red" data-delete="${esc(g.id)}">Excluir</button></div></div>`}).join('')||'<p>Nenhum grupo cadastrado.</p>';document.querySelectorAll('[data-copy-link]').forEach(b=>b.onclick=()=>copyText(b.dataset.copyLink,'Link rastreável copiado.'));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteGroup(b.dataset.delete))}
function trackingLink(g){return `${location.origin}/r?src=${encodeURIComponent(g.id||g.url)}&bairro=${encodeURIComponent(g.region||'')}`}
async function saveGroup(){const region=selectedRegion(),url=normUrl($('groupUrl').value),name=$('groupName').value.trim()||'Grupo Facebook';if(!region)return toast('Selecione o bairro.');if(!url)return toast('Informe um link válido de grupo.');if(state.groups.some(g=>g.url===url))return toast('Esse grupo já está cadastrado.');const item={id:'g_'+Date.now().toString(36)+Math.random().toString(36).slice(2),name,url,link:url,region,bairro:region,status:'pendente',postedAt:null,createdAt:new Date().toISOString()};state.groups.push(item);saveLocal();renderAll();$('groupName').value='';$('groupUrl').value='';try{await api('/api/groups',{method:'POST',body:JSON.stringify(item)})}catch(e){if(!/já está/.test(e.message))toast('Salvo no navegador; servidor será sincronizado depois.')}}
async function deleteGroup(id){if(!confirm('Excluir este grupo?'))return;const g=state.groups.find(x=>x.id===id);state.groups=state.groups.filter(x=>x.id!==id);saveLocal();renderAll();try{await api('/api/groups/delete',{method:'POST',body:JSON.stringify({id,url:g?.url})})}catch{}}
function buildSearches(){const region=selectedRegion();const niches=[...document.querySelectorAll('#searchNiches input:checked')].map(x=>x.value);state.searches=region?niches.map(n=>({title:`${n} ${region} RJ`,url:'https://www.google.com/search?q='+encodeURIComponent(`site:facebook.com/groups ${n} ${region} RJ`)})):[];$('massSearchTerms').value=state.searches.map(x=>x.title).join('\n');$('massSearchResults').innerHTML=state.searches.map(x=>`<div class="search-result-row"><div><strong>${esc(x.title)}</strong><br><small>${esc(x.url)}</small></div><a href="${esc(x.url)}" target="_blank">Abrir</a></div>`).join('')}
function extractLinks(){const region=selectedRegion();if(!region)return toast('Selecione o bairro antes de extrair.');const text=$('hunter2PasteBox').value;const matches=[...text.matchAll(/(?:https?:\/\/)?(?:www\.|m\.)?(?:facebook|fb)\.com\/groups\/[^\s<>"')]+/gi)].map(m=>m[0]);const map=new Map();matches.forEach(raw=>{const url=normUrl(raw);if(url&&!map.has(url)){const slug=(url.split('/groups/')[1]||'').replace(/[-_.]+/g,' ');map.set(url,{name:!slug||/^\d+$/.test(slug)?'Grupo Facebook':slug.replace(/\b\w/g,l=>l.toUpperCase()),url,region,selected:true})}});state.extracted=[...map.values()];renderExtracted()}
function renderExtracted(){$('hunter2Status').textContent=`${state.extracted.length} grupo(s) extraído(s) para ${selectedRegion()||'nenhum bairro'}.`;$('hunter2Results').innerHTML=state.extracted.map((g,i)=>`<div class="hunter2-row"><input type="checkbox" data-extract="${i}" ${g.selected?'checked':''}><div><strong>${esc(g.name)}</strong><small>${esc(g.url)}</small><span class="tag">${esc(g.region)}</span></div></div>`).join('')||'<p>Nenhum link extraído ainda.</p>';document.querySelectorAll('[data-extract]').forEach(c=>c.onchange=()=>state.extracted[Number(c.dataset.extract)].selected=c.checked)}
async function saveExtracted(){const selected=state.extracted.filter(x=>x.selected);if(!selected.length)return toast('Nenhum grupo selecionado.');let saved=0,dup=0;for(const x of selected){if(state.groups.some(g=>g.url===x.url)){dup++;continue}state.groups.push({id:'g_'+Date.now().toString(36)+Math.random().toString(36).slice(2),name:x.name,url:x.url,link:x.url,region:x.region,bairro:x.region,status:'pendente',postedAt:null,createdAt:new Date().toISOString()});saved++}saveLocal();renderAll();state.extracted=[];$('hunter2PasteBox').value='';renderExtracted();try{await api('/api/groups/backup',{method:'POST',body:JSON.stringify({groups:state.groups})})}catch{}toast(`${saved} grupos salvos. ${dup} repetidos.`)}
function eligible(g){return !g.postedAt||Date.now()-new Date(g.postedAt).getTime()>=DAY}
function startCycle(){const region=$('cycleRegionSelect').value;const limit=Math.max(1,Number($('cycleLimit').value||20));state.cycle=state.groups.filter(g=>(!region||g.region===region)&&eligible(g)).slice(0,limit);state.currentIndex=state.cycle.length?0:-1;state.current=state.cycle[0]||null;renderCycle();if(!state.current)toast('Nenhum grupo liberado para esse bairro.')}
function activeMessageCount(){return 4}
function currentMessage(){if(!state.current)return'';const index=((Number(state.messageIndex)||0)%4+4)%4;let text=String(state.models[index]||DEFAULT_MODELS[index]||'').trim();const link=trackingLink(state.current);return text.replaceAll('{LINK}',link).replaceAll('[LINK]',link).replaceAll('{{LINK}}',link)}
function refreshCurrentMessage(){const text=currentMessage();const main=$('currentCycleMessage');const dash=$('dashCurrentMessage');if(main)main.value=text;if(dash)dash.value=text;const label=$('currentMessageNumber');if(label)label.textContent=`Mensagem atual: ${state.messageIndex+1} de 4`;const dashLabel=$('dashMessageNumber');if(dashLabel)dashLabel.textContent=`Mensagem atual: ${state.messageIndex+1} de 4`}
function renderCycle(){const total=state.cycle.length;$('cycleProgress').textContent=state.current?`${state.currentIndex+1} / ${total}`:'0 / 0';const html=state.current?`<strong>${esc(state.current.name)}</strong><br><small>${esc(state.current.region)} · ${esc(state.current.url)}</small><br><small class="track-link">${esc(trackingLink(state.current))}</small>`:'Nenhum grupo no ciclo.';$('currentCycleGroup').innerHTML=html;$('dashCurrentGroup').innerHTML=html;refreshCurrentMessage();$('cycleList').innerHTML=state.cycle.map((g,i)=>`<div class="data-row ${i===state.currentIndex?'active-cycle':''}"><header><strong>${esc(g.name)}</strong><span>${eligible(g)?'liberado':'bloqueado 24h'}</span></header><small>${esc(g.region)} · ${esc(g.url)}</small></div>`).join('')||'<p>Nenhum grupo.</p>'}
function advance(){if(!state.cycle.length)return startCycle();if(state.currentIndex+1>=state.cycle.length)return toast('Fim do ciclo.');state.currentIndex++;state.current=state.cycle[state.currentIndex];renderCycle()}
function openCurrent(){if(!state.current)return toast('Inicie o ciclo.');window.open(state.current.url,'_blank')}
async function copyCurrent(){const t=currentMessage();if(!t)return toast('Cadastre uma mensagem e inicie o ciclo.');await copyText(t,'Mensagem copiada com link rastreável.')}
async function markPosted(){
  if(!state.current) return toast('Nenhum grupo atual. Inicie o ciclo primeiro.');

  const current = state.current;
  const postedAt = new Date().toISOString();
  const button = $('markPostedBtn');
  const dashButton = $('dashPostedBtn');

  [button,dashButton].filter(Boolean).forEach(b=>{b.disabled=true;b.dataset.oldText=b.textContent;b.textContent='Salvando...'});

  try{
    // Garante que o grupo existe no servidor antes de marcar.
    await api('/api/groups/backup',{
      method:'POST',
      body:JSON.stringify({groups:state.groups})
    });

    const response = await api('/api/groups/mark-posted',{
      method:'POST',
      body:JSON.stringify({id:current.id,url:current.url,link:current.url,postedAt})
    });

    if(!response.group){
      throw new Error('O servidor não encontrou o grupo para marcar.');
    }

    state.groups = mergeGroups(state.groups, response.groups || []);
    const real = state.groups.find(x=>x.id===current.id || x.url===current.url);
    if(real){
      real.status='postado';
      real.postedAt=response.group.postedAt || postedAt;
    }

    const usedMessage=((Number(state.messageIndex)||0)%4)+1;
    state.activity.unshift({text:`Postagem em ${current.name} com a mensagem ${usedMessage}`,at:postedAt});

    // Avança obrigatoriamente 1 → 2 → 3 → 4 → 1 somente após o servidor confirmar.
    state.messageIndex=((Number(state.messageIndex)||0)+1)%4;
    localStorage.setItem(STORE.messageIndex,JSON.stringify(state.messageIndex));
    saveLocal();

    // Atualiza imediatamente o texto e o contador visível antes de reconstruir a fila.
    refreshCurrentMessage();

    const region=$('cycleRegionSelect').value;
    const limit=Math.max(1,Number($('cycleLimit').value||20));
    state.cycle=state.groups.filter(x=>(!region||x.region===region)&&eligible(x)).slice(0,limit);
    state.currentIndex=state.cycle.length?0:-1;
    state.current=state.cycle[0]||null;
    renderAll();
    refreshCurrentMessage();
    toast(state.current?`Postado e salvo. Mensagem ${state.messageIndex+1} de 4 carregada.`:'Postado e salvo. Fim dos grupos liberados.');
  }catch(error){
    console.error('Erro ao marcar como postado:',error);
    toast('Não foi possível salvar como postado: '+(error.message||'erro desconhecido'));
  }finally{
    [button,dashButton].filter(Boolean).forEach(b=>{b.disabled=false;b.textContent=b.dataset.oldText||'Marcar como Postado'});
  }
}
function renderModels(){state.models.forEach((m,i)=>{const e=$('model'+(i+1));if(e&&document.activeElement!==e)e.value=m});$('dashModels').innerHTML=state.models.map((m,i)=>`<div class="model-item"><strong>Mensagem ${i+1}</strong><p>${esc(m||'Vazia')}</p></div>`).join('')}
function saveModels(){state.models=[1,2,3,4].map(i=>$('model'+i).value||'');saveLocal();renderModels();toast('Modelos salvos.')}
async function loadClicks(){try{const d=await api('/api/clicks');state.clicks=Array.isArray(d.clicks)?d.clicks:[]}catch{state.clicks=[]}}
function renderReports(){const byR={},byG={};state.clicks.forEach(c=>{const r=c.region||c.bairro||'Sem bairro',g=c.groupName||c.grupo||c.groupId||'Sem grupo';byR[r]=(byR[r]||0)+1;byG[g]=(byG[g]||0)+1});const topR=Object.entries(byR).sort((a,b)=>b[1]-a[1])[0],topG=Object.entries(byG).sort((a,b)=>b[1]-a[1])[0];$('totalClicks').textContent=state.clicks.length;$('topClickRegion').textContent=topR?.[0]||'-';$('topClickGroup').textContent=topG?.[0]||'-';$('clickReportsList').innerHTML=Object.entries(byR).sort((a,b)=>b[1]-a[1]).map(([r,n])=>`<div class="data-row"><strong>${esc(r)}</strong><span>${n} cliques</span></div>`).join('')||'<p>Nenhum clique registrado.</p>';$('reportsList').innerHTML=state.regions.map(r=>`<div class="data-row"><strong>${esc(r.name)}</strong><span>${countByRegion(r.name)} grupos</span></div>`).join('')}
function renderActivity(){$('recentActivity').innerHTML=state.activity.slice(0,8).map(a=>`<div class="activity-item">✅ ${esc(a.text)}<br><small>${new Date(a.at).toLocaleString('pt-BR')}</small></div>`).join('')||'<p>Nenhuma atividade recente.</p>'}
function renderAll(){renderStats();renderRegions();fillRegions();renderGroups();renderModels();renderCycle();renderReports();renderActivity();saveLocal()}
async function copyText(text,msg){await navigator.clipboard.writeText(text).catch(()=>{});toast(msg)}
function toast(msg){let e=document.getElementById('cleanToast');if(!e){e=document.createElement('div');e.id='cleanToast';document.body.appendChild(e)}e.textContent=msg;e.className='show';clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>e.className='',2200)}
function exportGroups(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({groups:state.groups},null,2)],{type:'application/json'}));a.download='ideal-toldos-grupos.json';a.click()}
function importGroups(file){const r=new FileReader();r.onload=async()=>{try{const d=JSON.parse(r.result);state.groups=mergeGroups(state.groups,d.groups||d);saveLocal();renderAll();await api('/api/groups/backup',{method:'POST',body:JSON.stringify({groups:state.groups})});toast('Banco importado.')}catch{toast('Arquivo inválido.')}};r.readAsText(file)}
function addRegion(){const name=$('newRegionName').value.trim();if(!name)return;state.regions.push({name,zone:$('newRegionZone').value,goal:Number($('newRegionGoal').value||50)});$('newRegionName').value='';renderAll()}
document.addEventListener('DOMContentLoaded',async()=>{loadLocal();await sync();renderAll();document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-page-go]').forEach(b=>b.onclick=()=>go(b.dataset.pageGo));$('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');$('groupRegionSelect').onchange=updateSelectedRegion;document.querySelectorAll('#searchNiches input').forEach(x=>x.onchange=buildSearches);$('saveGroupBtn').onclick=saveGroup;$('clearGroupFormBtn').onclick=()=>{$('groupName').value='';$('groupUrl').value='';$('groupMembers').value=''};$('generateMassSearchBtn').onclick=buildSearches;$('openMassSearchBtn').onclick=()=>state.searches.forEach((x,i)=>setTimeout(()=>window.open(x.url,'_blank'),i*450));$('copyMassSearchBtn').onclick=()=>copyText(state.searches.map(x=>x.url).join('\n'),'Buscas copiadas.');$('hunter2ExtractBtn').onclick=extractLinks;$('hunter2SelectAllBtn').onclick=()=>{state.extracted.forEach(x=>x.selected=true);renderExtracted()};$('hunter2SaveBtn').onclick=saveExtracted;$('hunter2ClearBtn').onclick=()=>{state.extracted=[];$('hunter2PasteBox').value='';renderExtracted()};$('filterGroups').oninput=renderGroups;$('exportGroupsBtn').onclick=exportGroups;$('importGroupsFile').onchange=e=>e.target.files[0]&&importGroups(e.target.files[0]);$('addRegionBtn').onclick=addRegion;$('loadDefaultRegionsBtn').onclick=()=>{state.regions=DEFAULT_REGIONS.map(name=>({name,zone:'Rio de Janeiro',goal:50}));renderAll()};$('resetRegionsBtn').onclick=()=>toast('A contagem é baseada nos grupos cadastrados e não precisa ser zerada.');$('saveModelsBtn').onclick=saveModels;$('startCycleBtn').onclick=startCycle;$('openNextBtn').textContent='Abrir Grupo';$('openNextBtn').onclick=openCurrent;$('dashNextBtn').textContent='Abrir Grupo';$('dashNextBtn').onclick=openCurrent;$('copyMessageBtn').onclick=copyCurrent;$('dashCopyBtn').onclick=copyCurrent;$('markPostedBtn').onclick=markPosted;$('dashPostedBtn').onclick=markPosted;$('resetCycleBtn').onclick=()=>{state.cycle=[];state.current=null;state.currentIndex=-1;renderCycle()};$('cycleRegionSelect').onchange=startCycle;$('dashRegionSelect').onchange=()=>{$('cycleRegionSelect').value=$('dashRegionSelect').value;startCycle()};$('exportDataBtn').onclick=exportGroups;$('saveIgnoredIpBtn')?.addEventListener('click',async()=>{try{await api('/api/settings/ignored-ip',{method:'POST',body:JSON.stringify({ip:$('adminIgnoredIp').value})});$('ignoredIpStatus').textContent='IP salvo.'}catch(e){toast(e.message)}});go('dashboard')});
